version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

